In [8]:
import numpy as np

### 1.	Create a 2D array and print the dim and shape

In [2]:
array2 = np.array([[333,777,9999], [11, 22, 33]])

In [3]:
array2.shape

(2, 3)

In [4]:
array2.ndim

2

### 2.	Create an array of 20 numbers using arange function and slice the values between 10 to 15

In [14]:
list1 = np.arange(20)
array3 = slice (10,15)
list1[array3]

array([10, 11, 12, 13, 14])

### 3.	Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using 
a.	Addition
b.	Subtraction
c.	Multiplication
d.	Division


In [15]:
x2 = np.array([[1,5,9,13,17],[2,6,10,14,18],[3,7,11,15,19],[4,8,12,16,20],[17,22,46,70,5], [18,52,34,42,21],[71,58,93,63,81]])
y2 = np.array([[11,15,19,13,16],[22,26,20,24,28],[33,37,31,35,39],[44,48,42,46,40],[58,56,57,54,59],[64,65,67,69,63],[7,9,3,6,23]]) 

In [16]:
x2.shape

(7, 5)

In [17]:
y2.shape

(7, 5)

##### a.Addition

In [22]:
z1=np.add(x2,y2)
z1

array([[ 12,  20,  28,  26,  33],
       [ 24,  32,  30,  38,  46],
       [ 36,  44,  42,  50,  58],
       [ 48,  56,  54,  62,  60],
       [ 75,  78, 103, 124,  64],
       [ 82, 117, 101, 111,  84],
       [ 78,  67,  96,  69, 104]])

#### b.Subtraction

In [24]:
z2= np.subtract(x2,y2)
z2

array([[-10, -10, -10,   0,   1],
       [-20, -20, -10, -10, -10],
       [-30, -30, -20, -20, -20],
       [-40, -40, -30, -30, -20],
       [-41, -34, -11,  16, -54],
       [-46, -13, -33, -27, -42],
       [ 64,  49,  90,  57,  58]])

#### c. Multiplication

In [25]:
z3=np.multiply(x2,y2)
z3

array([[  11,   75,  171,  169,  272],
       [  44,  156,  200,  336,  504],
       [  99,  259,  341,  525,  741],
       [ 176,  384,  504,  736,  800],
       [ 986, 1232, 2622, 3780,  295],
       [1152, 3380, 2278, 2898, 1323],
       [ 497,  522,  279,  378, 1863]])

#### d.Division

In [27]:
z4=np.divide(x2,y2)
z4

array([[ 0.09090909,  0.33333333,  0.47368421,  1.        ,  1.0625    ],
       [ 0.09090909,  0.23076923,  0.5       ,  0.58333333,  0.64285714],
       [ 0.09090909,  0.18918919,  0.35483871,  0.42857143,  0.48717949],
       [ 0.09090909,  0.16666667,  0.28571429,  0.34782609,  0.5       ],
       [ 0.29310345,  0.39285714,  0.80701754,  1.2962963 ,  0.08474576],
       [ 0.28125   ,  0.8       ,  0.50746269,  0.60869565,  0.33333333],
       [10.14285714,  6.44444444, 31.        , 10.5       ,  3.52173913]])

In [28]:
z5=np.divide(y2,x2)
z5

array([[11.        ,  3.        ,  2.11111111,  1.        ,  0.94117647],
       [11.        ,  4.33333333,  2.        ,  1.71428571,  1.55555556],
       [11.        ,  5.28571429,  2.81818182,  2.33333333,  2.05263158],
       [11.        ,  6.        ,  3.5       ,  2.875     ,  2.        ],
       [ 3.41176471,  2.54545455,  1.23913043,  0.77142857, 11.8       ],
       [ 3.55555556,  1.25      ,  1.97058824,  1.64285714,  3.        ],
       [ 0.09859155,  0.15517241,  0.03225806,  0.0952381 ,  0.28395062]])

### 4.	Create 2 incompatible arrays for broadcast and print out the error

In [31]:
x3 = np.array([[1,5,9,13,17],[2,6,10,14,18],[3,7,11,15,19],[4,8,12,16,20],[17,22,46,70,5], [71,58,93,63,81]])
y3 = np.array([[11,15,19,13,16],[22,26,20,24,28],[33,37,31,35,39],[44,48,42,46,40],[58,56,57,54,59],[64,65,67,69,63],[7,9,3,6,23]]) 
x3.shape

(6, 5)

In [32]:
y3.shape

(7, 5)

In [33]:
z = x3*y3

ValueError: operands could not be broadcast together with shapes (6,5) (7,5) 

### 5.	Create two arrays of any dimension and perform vstack and hstack

In [34]:
a1 = ([[1,2,3],[4,5,6],[7,8,9]])
b1 = ([[1,2,3],[4,5,6],[9,10,11]])

In [35]:
np.vstack((a1,b1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11]])

In [37]:
np.hstack((a1,b1))

array([[ 1,  2,  3,  1,  2,  3],
       [ 4,  5,  6,  4,  5,  6],
       [ 7,  8,  9,  9, 10, 11]])

### 6.	Append two arrays using axis = 0 and axis = 1

In [39]:
a2 = ([[1,2,3,9],[4,5,6,3],[7,8,9,1]])
b2 = ([[1,2,3,33],[4,5,6,66],[9,10,11,22]])
np.stack((a2,b2), axis = 0)

array([[[ 1,  2,  3,  9],
        [ 4,  5,  6,  3],
        [ 7,  8,  9,  1]],

       [[ 1,  2,  3, 33],
        [ 4,  5,  6, 66],
        [ 9, 10, 11, 22]]])

In [40]:
np.stack((a2,b2), axis = 1)

array([[[ 1,  2,  3,  9],
        [ 1,  2,  3, 33]],

       [[ 4,  5,  6,  3],
        [ 4,  5,  6, 66]],

       [[ 7,  8,  9,  1],
        [ 9, 10, 11, 22]]])

### 7.	Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation

In [41]:
import pandas as pd

In [44]:
list1 = [[1,'Shri',99,88], [2,'Reena',100,89], [3,'Vani',98,88], [4,'Sarita',99,78],[5,'Rekha',79,67],[6,'Vrita',88,90],[7,'Priya',94,92],[8,'Gomathi',96,78]]
list1
np.shape(list1)

(8, 4)

In [45]:
df = pd.DataFrame(list1, columns = ['ID','Name','Maths Marks', 'Science Marks'])
df

ID     Name  Maths Marks  Science Marks
0   1     Shri           99             88
1   2    Reena          100             89
2   3     Vani           98             88
3   4   Sarita           99             78
4   5    Rekha           79             67
5   6    Vrita           88             90
6   7    Priya           94             92
7   8  Gomathi           96             78

### 8.	Create a dataframe of 4 X 8 dimension using a dictionary

In [49]:
dic1 = {
    "ID" :[1,2,3,4,5,6,7,8],
    "Storeid" : ['340001','230134','8111234','3400003','6500321','54008732','4586372','76320834'],
    "Sales" : [100000,2000000,3000000,4000000,5000000,6000000,7000000,8000000],
    "Status" : ['Gain','Loss','Gain','Loss','Gain','Loss','Gain','Loss']    
}
df1 = pd.DataFrame(dic1, index = [1,2,3,4,5,6,7,8])
df1

ID   Storeid    Sales Status
1   1    340001   100000   Gain
2   2    230134  2000000   Loss
3   3   8111234  3000000   Gain
4   4   3400003  4000000   Loss
5   5   6500321  5000000   Gain
6   6  54008732  6000000   Loss
7   7   4586372  7000000   Gain
8   8  76320834  8000000   Loss

### 9.	Use loc and iloc to subset the data for the above dataframe

In [51]:
df1.index = ('A','B','C','D','E','F','G','H')
df1

ID   Storeid    Sales Status
A   1    340001   100000   Gain
B   2    230134  2000000   Loss
C   3   8111234  3000000   Gain
D   4   3400003  4000000   Loss
E   5   6500321  5000000   Gain
F   6  54008732  6000000   Loss
G   7   4586372  7000000   Gain
H   8  76320834  8000000   Loss

In [53]:
df1.loc['B':'E', ['Storeid','Sales']]

Storeid    Sales
B   230134  2000000
C  8111234  3000000
D  3400003  4000000
E  6500321  5000000

In [54]:
df1

ID   Storeid    Sales Status
A   1    340001   100000   Gain
B   2    230134  2000000   Loss
C   3   8111234  3000000   Gain
D   4   3400003  4000000   Loss
E   5   6500321  5000000   Gain
F   6  54008732  6000000   Loss
G   7   4586372  7000000   Gain
H   8  76320834  8000000   Loss

In [55]:
df1.iloc[1:2]

ID Storeid    Sales Status
B   2  230134  2000000   Loss

In [56]:
df1.iloc[0:2, 1:2]

Storeid
A  340001
B  230134

In [57]:
df1.iloc[:6]

ID   Storeid    Sales Status
A   1    340001   100000   Gain
B   2    230134  2000000   Loss
C   3   8111234  3000000   Gain
D   4   3400003  4000000   Loss
E   5   6500321  5000000   Gain
F   6  54008732  6000000   Loss

### 10.	How to check the total number of not null values in a column?

In [59]:
df2 = pd.DataFrame(np.random.randn(5,3),index = ['A','B','e','f','h'], columns = ['One', 'Two', 'Three'])
df2

One       Two     Three
A -0.917840  0.344697 -1.010960
B  0.379705  0.772407 -2.009884
e -1.085200 -0.258429 -0.570322
f -1.622769  0.346355 -0.770904
h  1.511904  0.118025  0.732404

In [61]:
df2['One'].isnull()

A    False
B    False
e    False
f    False
h    False
Name: One, dtype: bool

In [62]:
df2['Two'].isnull().sum()

0

In [63]:
df2['Three'].isnull()

A    False
B    False
e    False
f    False
h    False
Name: Three, dtype: bool

In [75]:
list2 = [[1,'Shri',99,88], [2,'Reena',100,np.nan], [3,'Vani',98,np.nan], [4,'Sarita',99,78],[5,'Rekha',np.nan,67],[6,'Vrita',88,90],[7,'Priya',94,92],[8,'Gomathi',96,78]]
list2
df3 = pd.DataFrame (list2, columns = ['Id', 'Name', 'Mark1', 'Mark2'])
df3

Id     Name  Mark1  Mark2
0   1     Shri   99.0   88.0
1   2    Reena  100.0    NaN
2   3     Vani   98.0    NaN
3   4   Sarita   99.0   78.0
4   5    Rekha    NaN   67.0
5   6    Vrita   88.0   90.0
6   7    Priya   94.0   92.0
7   8  Gomathi   96.0   78.0

In [76]:
df3['Mark1'].isnull()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
Name: Mark1, dtype: bool

In [77]:
df3['Mark2'].isnull().sum()

2

### 11.	Create a dataframe with missing values and fill them all with 100

In [78]:
dic2 = {
    "ID" :[1,2,3,4,5,6,7,8],
    "State" : ['TamilNadu','Kerala','Karnataka','Andhra','Telungana','Maharashtra',np.nan,np.nan],
    "Revenue" : [900,700,np.nan,400,np.nan,600,300,np.nan],
    "Debt" : ['Yes','No','Yes','No','Yes','No','No','Yes']    
}
df4 = pd.DataFrame(dic2, index = [1,2,3,4,5,6,7,8])
df4

ID        State  Revenue Debt
1   1    TamilNadu    900.0  Yes
2   2       Kerala    700.0   No
3   3    Karnataka      NaN  Yes
4   4       Andhra    400.0   No
5   5    Telungana      NaN  Yes
6   6  Maharashtra    600.0   No
7   7          NaN    300.0   No
8   8          NaN      NaN  Yes

##### using fillna

In [84]:
df4['Revenue'].fillna(100)

1    900.0
2    700.0
3    100.0
4    400.0
5    100.0
6    600.0
7    300.0
8    100.0
Name: Revenue, dtype: float64

##### Using np.where

In [86]:
df4['State'] = np.where(df4['ID'] == 7, 'Orissa', df4['State'])
df4['State'] = np.where(df4['ID'] == 8, 'Assam', df4['State'])
df4


ID        State  Revenue Debt
1   1    TamilNadu    900.0  Yes
2   2       Kerala    700.0   No
3   3    Karnataka      NaN  Yes
4   4       Andhra    400.0   No
5   5    Telungana      NaN  Yes
6   6  Maharashtra    600.0   No
7   7       Orissa    300.0   No
8   8        Assam      NaN  Yes

### 12.	Create a dataframe with missing values and drop the null records

In [87]:
dic3 = {
    "S.No." :[1,2,3,4,5,6,7,8],
    "Employee Name" : ['Ravi','Ratchel',np.nan,'Rani','Raghav','Reema',np.nan,'Riya'],
    "Salary" : [900000,70000,np.nan,400000,np.nan,600000,3000000,np.nan],
    "Department" : ['CS','HR','Sale','Finance','CS','Revenue','HR','Sale']    
}
df5 = pd.DataFrame(dic3, index = [1,2,3,4,5,6,7,8])
df5

S.No. Employee Name     Salary Department
1      1          Ravi   900000.0         CS
2      2       Ratchel    70000.0         HR
3      3           NaN        NaN       Sale
4      4          Rani   400000.0    Finance
5      5        Raghav        NaN         CS
6      6         Reema   600000.0    Revenue
7      7           NaN  3000000.0         HR
8      8          Riya        NaN       Sale

In [88]:
df5.dropna()

S.No. Employee Name    Salary Department
1      1          Ravi  900000.0         CS
2      2       Ratchel   70000.0         HR
4      4          Rani  400000.0    Finance
6      6         Reema  600000.0    Revenue

### 13.	Perform following aggregation task on below table
a.	Get the average age group by Regrion
b.	Get the sum of Age and Validation group by Hair color and then reset the index
c.	Get the man and the median of Age group by Region


In [20]:
import numpy as np
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')

In [7]:
dic4 = {
    "Age" :[25,30,45,35,33,35,25,52,21,24,48,22,27,28,21,51,23],
    "Hair Colour" : ['Black','Black','Red','Blond','Brown','Brown','Black','Brown','Blond','Blond','Black','Black','Brown','Black','Blond','Black','Brown'],
    "U.S. Region" : ['Southwest','Northwest','Northeast','Southwest','Southwest','Northeast','Southwest','Southeast','Southwest','Northeast','Southwest','Southwest','Northeast','Southeast','Southeast','Northwest','Southeast'],
    "Validation" : [1,1,1,0,0,0,0,0,1,0,1,0,0,1,1,0,1]    
}
df6 = pd.DataFrame(dic4)
df6

Age Hair Colour U.S. Region  Validation
0    25       Black   Southwest           1
1    30       Black   Northwest           1
2    45         Red   Northeast           1
3    35       Blond   Southwest           0
4    33       Brown   Southwest           0
5    35       Brown   Northeast           0
6    25       Black   Southwest           0
7    52       Brown   Southeast           0
8    21       Blond   Southwest           1
9    24       Blond   Northeast           0
10   48       Black   Southwest           1
11   22       Black   Southwest           0
12   27       Brown   Northeast           0
13   28       Black   Southeast           1
14   21       Blond   Southeast           1
15   51       Black   Northwest           0
16   23       Brown   Southeast           1

##### a. Get the average age group by Region

In [11]:
df6.groupby(['U.S. Region'])['Age'].mean()

U.S. Region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: Age, dtype: float64

##### b.	Get the sum of Age and Validation group by Hair color and then reset the index

In [15]:
df6.groupby(['Hair Colour']) ['Age', 'Validation'].sum().reset_index()

Hair Colour  Age  Validation
0       Black  229           4
1       Blond  101           2
2       Brown  170           1
3         Red   45           1

##### c.	Get the mean and the median of Age group by Region


In [16]:
df6.groupby(['U.S. Region'])['Age'].mean()

U.S. Region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: Age, dtype: float64

In [17]:
df6.groupby(['U.S. Region'])['Age'].median()

U.S. Region
Northeast    31.0
Northwest    40.5
Southeast    25.5
Southwest    25.0
Name: Age, dtype: float64

### 14.	Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)

In [22]:
dic5 = {
    "Age" :[25,30,45,35,33,35,25,52,21],
    "Hair Colour" : ['Black','Black','Red','Blond','Brown','Brown','Black','Brown','Blond'],
    "U.S. Region" : ['Southwest','Northwest','Northeast','Northeast','Southwest','Southwest','Northeast','Southeast','Southeast'],
    "Validation" : [1,1,1,0,0,0,0,0,1]    
}
df_left = pd.DataFrame(dic5)
df_left

Age Hair Colour U.S. Region  Validation
0   25       Black   Southwest           1
1   30       Black   Northwest           1
2   45         Red   Northeast           1
3   35       Blond   Northeast           0
4   33       Brown   Southwest           0
5   35       Brown   Southwest           0
6   25       Black   Northeast           0
7   52       Brown   Southeast           0
8   21       Blond   Southeast           1

In [23]:
dic6 = {
    "Age" :[24,48,22,27,28,21,51,23],
    "Hair Colour" : ['Blond','Black','Black','Brown','Black','Blond','Black','Brown'],
    "U.S. Region" : ['Northeast','Southwest','Southwest','Northeast','Southeast','Southeast','Northwest','Southeast'],
    "Validation" : [0,1,0,0,1,1,0,1]    
}
df_right = pd.DataFrame(dic6)
df_right

Age Hair Colour U.S. Region  Validation
0   24       Blond   Northeast           0
1   48       Black   Southwest           1
2   22       Black   Southwest           0
3   27       Brown   Northeast           0
4   28       Black   Southeast           1
5   21       Blond   Southeast           1
6   51       Black   Northwest           0
7   23       Brown   Southeast           1

In [24]:
## Inner
pd.merge(df_left, df_right, on='U.S. Region')


Age_x Hair Colour_x U.S. Region  Validation_x  Age_y Hair Colour_y  \
0      25         Black   Southwest             1     48         Black   
1      25         Black   Southwest             1     22         Black   
2      33         Brown   Southwest             0     48         Black   
3      33         Brown   Southwest             0     22         Black   
4      35         Brown   Southwest             0     48         Black   
5      35         Brown   Southwest             0     22         Black   
6      30         Black   Northwest             1     51         Black   
7      45           Red   Northeast             1     24         Blond   
8      45           Red   Northeast             1     27         Brown   
9      35         Blond   Northeast             0     24         Blond   
10     35         Blond   Northeast             0     27         Brown   
11     25         Black   Northeast             0     24         Blond   
12     25         Black   Northeast             0     27         Brown   
13     52         Brown   Southeast             0     28         Black   
14     52         Brown   Southeast             0     21         Blond   
15     52         Brown   Southeast             0     23         Brown   
16     21         Blond   Southeast             1     28         Black   
17     21         Blond   Southeast             1     21         Blond   
18     21         Blond   Southeast             1     23         Brown   

    Validation_y  
0              1  
1              0  
2              1  
3              0  
4              1  
5              0  
6              0  
7              0  
8              0  
9              0  
10             0  
11             0  
12             0  
13             1  
14             1  
15             1  
16             1  
17             1  
18             1

In [26]:
#Left
df_left.merge(df_right, on='U.S. Region', how = 'left')

Age_x Hair Colour_x U.S. Region  Validation_x  Age_y Hair Colour_y  \
0      25         Black   Southwest             1     48         Black   
1      25         Black   Southwest             1     22         Black   
2      30         Black   Northwest             1     51         Black   
3      45           Red   Northeast             1     24         Blond   
4      45           Red   Northeast             1     27         Brown   
5      35         Blond   Northeast             0     24         Blond   
6      35         Blond   Northeast             0     27         Brown   
7      33         Brown   Southwest             0     48         Black   
8      33         Brown   Southwest             0     22         Black   
9      35         Brown   Southwest             0     48         Black   
10     35         Brown   Southwest             0     22         Black   
11     25         Black   Northeast             0     24         Blond   
12     25         Black   Northeast             0     27         Brown   
13     52         Brown   Southeast             0     28         Black   
14     52         Brown   Southeast             0     21         Blond   
15     52         Brown   Southeast             0     23         Brown   
16     21         Blond   Southeast             1     28         Black   
17     21         Blond   Southeast             1     21         Blond   
18     21         Blond   Southeast             1     23         Brown   

    Validation_y  
0              1  
1              0  
2              0  
3              0  
4              0  
5              0  
6              0  
7              1  
8              0  
9              1  
10             0  
11             0  
12             0  
13             1  
14             1  
15             1  
16             1  
17             1  
18             1

In [28]:
#Right
df_left.merge(df_left, on='U.S. Region', how = 'left')

Age_x Hair Colour_x U.S. Region  Validation_x  Age_y Hair Colour_y  \
0      25         Black   Southwest             1     25         Black   
1      25         Black   Southwest             1     33         Brown   
2      25         Black   Southwest             1     35         Brown   
3      30         Black   Northwest             1     30         Black   
4      45           Red   Northeast             1     45           Red   
5      45           Red   Northeast             1     35         Blond   
6      45           Red   Northeast             1     25         Black   
7      35         Blond   Northeast             0     45           Red   
8      35         Blond   Northeast             0     35         Blond   
9      35         Blond   Northeast             0     25         Black   
10     33         Brown   Southwest             0     25         Black   
11     33         Brown   Southwest             0     33         Brown   
12     33         Brown   Southwest             0     35         Brown   
13     35         Brown   Southwest             0     25         Black   
14     35         Brown   Southwest             0     33         Brown   
15     35         Brown   Southwest             0     35         Brown   
16     25         Black   Northeast             0     45           Red   
17     25         Black   Northeast             0     35         Blond   
18     25         Black   Northeast             0     25         Black   
19     52         Brown   Southeast             0     52         Brown   
20     52         Brown   Southeast             0     21         Blond   
21     21         Blond   Southeast             1     52         Brown   
22     21         Blond   Southeast             1     21         Blond   

    Validation_y  
0              1  
1              0  
2              0  
3              1  
4              1  
5              0  
6              0  
7              1  
8              0  
9              0  
10             1  
11             0  
12             0  
13             1  
14             0  
15             0  
16             1  
17             0  
18             0  
19             0  
20             1  
21             0  
22             1

In [29]:
#Right
df_left.merge(df_right, on='U.S. Region', how = 'right')

Age_x Hair Colour_x U.S. Region  Validation_x  Age_y Hair Colour_y  \
0      45           Red   Northeast             1     24         Blond   
1      35         Blond   Northeast             0     24         Blond   
2      25         Black   Northeast             0     24         Blond   
3      25         Black   Southwest             1     48         Black   
4      33         Brown   Southwest             0     48         Black   
5      35         Brown   Southwest             0     48         Black   
6      25         Black   Southwest             1     22         Black   
7      33         Brown   Southwest             0     22         Black   
8      35         Brown   Southwest             0     22         Black   
9      45           Red   Northeast             1     27         Brown   
10     35         Blond   Northeast             0     27         Brown   
11     25         Black   Northeast             0     27         Brown   
12     52         Brown   Southeast             0     28         Black   
13     21         Blond   Southeast             1     28         Black   
14     52         Brown   Southeast             0     21         Blond   
15     21         Blond   Southeast             1     21         Blond   
16     30         Black   Northwest             1     51         Black   
17     52         Brown   Southeast             0     23         Brown   
18     21         Blond   Southeast             1     23         Brown   

    Validation_y  
0              0  
1              0  
2              0  
3              1  
4              1  
5              1  
6              0  
7              0  
8              0  
9              0  
10             0  
11             0  
12             1  
13             1  
14             1  
15             1  
16             0  
17             1  
18             1

In [30]:
#Right
df_left.merge(df_left, on='U.S. Region', how = 'right')

Age_x Hair Colour_x U.S. Region  Validation_x  Age_y Hair Colour_y  \
0      25         Black   Southwest             1     25         Black   
1      33         Brown   Southwest             0     25         Black   
2      35         Brown   Southwest             0     25         Black   
3      30         Black   Northwest             1     30         Black   
4      45           Red   Northeast             1     45           Red   
5      35         Blond   Northeast             0     45           Red   
6      25         Black   Northeast             0     45           Red   
7      45           Red   Northeast             1     35         Blond   
8      35         Blond   Northeast             0     35         Blond   
9      25         Black   Northeast             0     35         Blond   
10     25         Black   Southwest             1     33         Brown   
11     33         Brown   Southwest             0     33         Brown   
12     35         Brown   Southwest             0     33         Brown   
13     25         Black   Southwest             1     35         Brown   
14     33         Brown   Southwest             0     35         Brown   
15     35         Brown   Southwest             0     35         Brown   
16     45           Red   Northeast             1     25         Black   
17     35         Blond   Northeast             0     25         Black   
18     25         Black   Northeast             0     25         Black   
19     52         Brown   Southeast             0     52         Brown   
20     21         Blond   Southeast             1     52         Brown   
21     52         Brown   Southeast             0     21         Blond   
22     21         Blond   Southeast             1     21         Blond   

    Validation_y  
0              1  
1              1  
2              1  
3              1  
4              1  
5              1  
6              1  
7              0  
8              0  
9              0  
10             0  
11             0  
12             0  
13             0  
14             0  
15             0  
16             0  
17             0  
18             0  
19             0  
20             0  
21             1  
22             1

### 15.	Split the below table and perform concat row wise and column wise

In [31]:
 #Concat Column wise operation
pd.concat([df_left, df_right], axis=1)

Age Hair Colour U.S. Region  Validation   Age Hair Colour U.S. Region  \
0   25       Black   Southwest           1  24.0       Blond   Northeast   
1   30       Black   Northwest           1  48.0       Black   Southwest   
2   45         Red   Northeast           1  22.0       Black   Southwest   
3   35       Blond   Northeast           0  27.0       Brown   Northeast   
4   33       Brown   Southwest           0  28.0       Black   Southeast   
5   35       Brown   Southwest           0  21.0       Blond   Southeast   
6   25       Black   Northeast           0  51.0       Black   Northwest   
7   52       Brown   Southeast           0  23.0       Brown   Southeast   
8   21       Blond   Southeast           1   NaN         NaN         NaN   

   Validation  
0         0.0  
1         1.0  
2         0.0  
3         0.0  
4         1.0  
5         1.0  
6         0.0  
7         1.0  
8         NaN

In [32]:
 #Concat Row wise operation
pd.concat([df_left, df_right])

Age Hair Colour U.S. Region  Validation
0   25       Black   Southwest           1
1   30       Black   Northwest           1
2   45         Red   Northeast           1
3   35       Blond   Northeast           0
4   33       Brown   Southwest           0
5   35       Brown   Southwest           0
6   25       Black   Northeast           0
7   52       Brown   Southeast           0
8   21       Blond   Southeast           1
0   24       Blond   Northeast           0
1   48       Black   Southwest           1
2   22       Black   Southwest           0
3   27       Brown   Northeast           0
4   28       Black   Southeast           1
5   21       Blond   Southeast           1
6   51       Black   Northwest           0
7   23       Brown   Southeast           1